fruits = ("apple" , "banana" , "coconut"  , "apple" , )
vegetables = ("tomato" , "cucumber" , "potato" , "salad")
#print(dir(fruits))
#print(help(fruits))
print(fruits.index("apple"))
print(fruits.count("apple"))
print(len(fruits))
print("tomato" in vegetables)
print(fruits.count("banana"))
print(fruits)